export const ADD_ITEM = 'ADD_ITEM';
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const DELETE_ITEM = 'DELETE_ITEM';
export const UNDO_REMOVE_DELETED_TODO = 'UNDO_REMOVE_DELETED_TODO';
export const ORDER_LIST = 'ORDER_LIST';
